name: main
on: push
env:
    DOIT_NUM_PROCESS: 0
jobs:
    main:
        runs-on: ubuntu-latest
        steps:
          - name: checkout repository
            uses: actions/checkout@v2
          - name: install ubuntu requirements
            run: |
                sudo apt update
                sudo apt install -q -y $(< requirements.github.ubuntu.txt)
          - name: install python
            uses: actions/setup-python@v1
            with:
                python-version: "3.10"
          - name: install python requirements
            run: |
                python -m pip install --upgrade pip
                pip install -e '.[dev]'
          - name: doit check
            run: doit check
          - name: doit test
            run: doit test
